
/* Inicia creacion de objetos necesarios */
DROP DATABASE IF EXISTS tiempoairedb;
CREATE DATABASE tiempoairedb;
use tiempoairedb;

DROP TABLE IF EXISTS TCPROVEEDORTELE;
DROP TABLE IF EXISTS TCPAQUETES;
DROP TABLE IF EXISTS TAVENTASPAQUETES;
DROP TABLE IF EXISTS TAVENTASPAQUETES;

CREATE TABLE TCPROVEEDORTELE(FIIDPROVEEDOR INT PRIMARY KEY,
					FCNOMBRE VARCHAR(20),
                    FCURLWSCOMPRAPAQ VARCHAR(100),
                    FIESTATUS INT,
					FDFECHAALTA TIMESTAMP NOT NULL,
                    FDFECHAMODIFICACION TIMESTAMP NOT NULL,
                    FCUSUARIO VARCHAR(15)
);

CREATE TABLE TCPAQUETES(FIIDPROVEEDOR INT,
					FIMONTO INT,
                    FCDESCRIPCION VARCHAR(50),
                    FIESTATUS INT,
					FDFECHAALTA TIMESTAMP NOT NULL,
                    FDFECHAMODIFICACION TIMESTAMP NOT NULL,
                    FCUSUARIO VARCHAR(15)
);

CREATE TABLE TAVENTASPAQUETES(FIIDIDENTIFICADOR INT AUTO_INCREMENT PRIMARY KEY,
					FIIDPROVEEDOR INT NOT NULL,
                    FIMONTO INT NOT NULL,
                    FITELEFONO LONG NOT NULL,
					FDFECHAVENTA TIMESTAMP NOT NULL,
					FISEMANA INT,
                    FIANIO INT
);
COMMIT;

/* Eliminamos los procedures en caso que existan */
DROP procedure IF EXISTS `SPOBTENERPROVEEDORES`;
DROP procedure IF EXISTS `SPOBTENERWSPROVEEDOR`;
DROP procedure IF EXISTS `SPOBTPAQTIEMPOAIRE`;
DROP procedure IF EXISTS `SPOBTPAQTIEMPOAIREXPROVEEDOR`;
DROP procedure IF EXISTS `SPCOMPRARTIEMPOAIRE`;
DROP procedure IF EXISTS `SPOBTDETALLEVENTAXPERIODOTIEMPO`;
DROP procedure IF EXISTS `SPOBTVENTASXPROVEEDORDELDIA`;
DROP procedure IF EXISTS `SPOBTVENTASXPROVEEDORMONTODELDIA`;
COMMIT;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPOBTENERPROVEEDORES`()
BEGIN
	/* Procedure para obtener los proveedores registrados */
    SET @rank = 0;
    
	SELECT
    @rank:=@rank+1 AS IDROW
    , FIIDPROVEEDOR
    , FCNOMBRE
    , FCURLWSCOMPRAPAQ
    , FIESTATUS
    , FDFECHAALTA
    FROM TCPROVEEDORTELE;
END
$$
DELIMITER ;


DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPOBTENERWSPROVEEDOR`(
IN PA_IDPROVEEDOR INT
)
BEGIN
	/* Procedure para obtener la URL del servicio de compra de un proveedor */
    SET @rank = 0;

    SELECT 
		@rank:=@rank+1 AS IDROW
	    , FIIDPROVEEDOR
		, FCNOMBRE
		, FCURLWSCOMPRAPAQ
		, FIESTATUS
		, FDFECHAALTA
	FROM TCPROVEEDORTELE
	WHERE FIIDPROVEEDOR=PA_IDPROVEEDOR
	AND FIESTATUS=1;
END
$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPOBTPAQTIEMPOAIRE`()
BEGIN
	/* Procedure para obtener los paquetes de tiempo aire 
		con los que cuenta los proveedores registrados */
	SET @rank = 0;
        
	SELECT 
		@rank:=@rank+1 AS IDROW
		, TP.FIIDPROVEEDOR
        , TP.FCNOMBRE
		, TT.FIMONTO
		, TT.FCDESCRIPCION
		, TT.FIESTATUS
    FROM TCPROVEEDORTELE TP
    , TCPAQUETES TT
    WHERE TP.FIIDPROVEEDOR=TT.FIIDPROVEEDOR
    AND TP.FIESTATUS=1
    AND TP.FIESTATUS=1;
END
$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPOBTPAQTIEMPOAIREXPROVEEDOR`(
IN PA_IDPROVEEDOR INT
)
BEGIN
	/* Procedure para obtener los paquetes de tiempo aire 
		con los que cuenta un proveedores en especifico*/
	SET @rank = 0;
        
	SELECT 
		@rank:=@rank+1 AS IDROW
		, TP.FIIDPROVEEDOR
        , TP.FCNOMBRE
		, TT.FIMONTO
		, TT.FCDESCRIPCION
		, TT.FIESTATUS
    FROM TCPROVEEDORTELE TP
    , TCPAQUETES TT
    WHERE TP.FIIDPROVEEDOR=TT.FIIDPROVEEDOR
    AND TP.FIIDPROVEEDOR=PA_IDPROVEEDOR
    AND TP.FIESTATUS=1
    AND TP.FIESTATUS=1;
END
$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPCOMPRARTIEMPOAIRE`(
IN PA_IDPROVEEDOR INT
, IN PA_MONTO INT
, IN PA_TELEFONO LONG
, OUT PA_CODEERROR INT
, OUT PA_MENSAJE VARCHAR(100)
)
BEGIN
	DECLARE EXISTEPAQUETE INT DEFAULT 0;
	DECLARE MINUTOSTRANSCURRIDOS INT;
    DECLARE MENSAJEINICIAL VARCHAR(100);
    
    SELECT
    TT.FIESTATUS
    INTO EXISTEPAQUETE
	FROM TCPROVEEDORTELE TP
	INNER JOIN TCPAQUETES TT
	ON TT.FIIDPROVEEDOR=TP.FIIDPROVEEDOR
	WHERE TP.FIIDPROVEEDOR=1
	AND TT.FIMONTO=PA_MONTO
	AND TT.FIESTATUS=1;
    
    IF (EXISTEPAQUETE>0) THEN
		SELECT 
		TIMESTAMPDIFF(MINUTE, A.FDFECHAVENTA, NOW()) as MINUTOSTRANSCURRIDOS 
		INTO MINUTOSTRANSCURRIDOS
		FROM(
		SELECT MAX(FDFECHAVENTA) AS FDFECHAVENTA FROM TAVENTASPAQUETES
		WHERE FITELEFONO=PA_TELEFONO AND FIMONTO=PA_MONTO
		) A;

		IF (MINUTOSTRANSCURRIDOS<16) THEN
			SET PA_CODEERROR = -1;
			SET MENSAJEINICIAL = CONCAT('El telefono ', PA_TELEFONO, ' recientemente realizo compra del paquete ');
			SET PA_MENSAJE = CONCAT(MENSAJEINICIAL, '', PA_MONTO);
		ELSE
			/* Procedure para registrar la compra de tiempo aire */
			INSERT INTO TAVENTASPAQUETES(FIIDPROVEEDOR
				, FIMONTO
				, FITELEFONO
				, FDFECHAVENTA
				, FISEMANA
				, FIANIO)
			VALUES (
			PA_IDPROVEEDOR
			, PA_MONTO
			, PA_TELEFONO
			, NOW()
			, WEEKOFYEAR(NOW())
			, YEAR(NOW())
			);
			
			COMMIT;
			
			SET PA_CODEERROR = 0;
			SET PA_MENSAJE = 'Compra realizada';
		END IF;
	ELSE
		/* Proveedor no cuenta con ese paquete para compra, o el paquete esta inactivo	*/
		SET PA_CODEERROR = -1;
		SET PA_MENSAJE = CONCAT('El proveedor no tiene disponible el paquete ', PA_MONTO, ', compra no realizada');
    END IF;
END
$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPOBTDETALLEVENTAXPERIODOTIEMPO`(
IN PA_DIAINICIO VARCHAR(10),
IN PA_DIAFIN VARCHAR(10)
)
BEGIN
	/* Procedure para obtener el detalle de las
	   ventas realizadas por un periodo de tiempo.
		La ultima fila pretende realizar la suma total*/
	SET @rank = 0;

	(SELECT
        @rank:=@rank+1 AS IDROW
		, TP.FIIDPROVEEDOR
		, TP.FCNOMBRE
        , TV.FIMONTO
        , DATE(TV.FDFECHAVENTA) AS FDFECHAVENTA
        , TV.FISEMANA
        , TV.FIANIO
		FROM TAVENTASPAQUETES TV
		INNER JOIN TCPROVEEDORTELE TP
		ON TV.FIIDPROVEEDOR=TP.FIIDPROVEEDOR
		WHERE DATE(TV.FDFECHAVENTA) BETWEEN DATE(PA_DIAINICIO) AND DATE(PA_DIAFIN)
        ORDER BY TP.FIIDPROVEEDOR, FDFECHAVENTA
     )  
     UNION ALL
      (  SELECT
		-1 AS IDROW
        , -1
        , 'TOTAL'
        , COALESCE(SUM(TV.FIMONTO), 0)
        , NULL
        , 0
        , 0
		FROM TAVENTASPAQUETES TV
		INNER JOIN TCPROVEEDORTELE TP
		ON TV.FIIDPROVEEDOR=TP.FIIDPROVEEDOR
		WHERE DATE(TV.FDFECHAVENTA) BETWEEN DATE(PA_DIAINICIO) AND DATE(PA_DIAFIN)
        );

END
$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPOBTVENTASXPROVEEDORDELDIA`()
BEGIN
	/* Procedure para obtener las ventas del día actual */
    SET @rank = 0;
    
	SELECT
    @rank:=@rank+1 AS IDROW
	, TP.FIIDPROVEEDOR
	, TP.FCNOMBRE
	, SUM(TV.FIMONTO) FITOTALVENTA
	FROM TAVENTASPAQUETES TV
	INNER JOIN TCPROVEEDORTELE TP
	ON TV.FIIDPROVEEDOR=TP.FIIDPROVEEDOR
	WHERE DATE(TV.FDFECHAVENTA)=DATE(SYSDATE()) 
    GROUP BY TP.FIIDPROVEEDOR, TP.FCNOMBRE;
END
$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SPOBTVENTASXPROVEEDORMONTODELDIA`()
BEGIN
	/* Procedure para obtener las venta toal de cada proveedore */
    
    SET @rank=0;
    
	SELECT
    @rank:=@rank+1 AS IDROW
	, TP.FIIDPROVEEDOR
	, TP.FCNOMBRE
    , TV.FIMONTO FIPAQUETE
	, SUM(TV.FIMONTO) FITOTALVENTA
	FROM TAVENTASPAQUETES TV
	INNER JOIN TCPROVEEDORTELE TP
	ON TV.FIIDPROVEEDOR=TP.FIIDPROVEEDOR
	WHERE DATE(TV.FDFECHAVENTA)=DATE(SYSDATE()) 
    GROUP BY TP.FIIDPROVEEDOR, TV.FIMONTO, TP.FCNOMBRE
    ORDER BY TP.FIIDPROVEEDOR, TP.FCNOMBRE, FIPAQUETE;
END
$$
DELIMITER ;

COMMIT;
/* Fin de creacion de objetos */



/* Registros de ejemplos */
TRUNCATE TCPROVEEDORTELE;
TRUNCATE TCPAQUETES;

/* Registramos unos proveedores */
/* Cada proveedor tendra la siguiente URL, para simular la compra*/
/* http://localhost:8080/WSTiempoAire/paqTiempoAire/{idProveedor}/comprar*/

INSERT INTO TCPROVEEDORTELE(FIIDPROVEEDOR, FCNOMBRE, FCURLWSCOMPRAPAQ, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(1, 'TELCEL', 'http://localhost:8080/WSTiempoAire/paqTiempoAire/1/comprar',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPROVEEDORTELE(FIIDPROVEEDOR, FCNOMBRE, FCURLWSCOMPRAPAQ, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(2, 'MOVISTAR', 'http://localhost:8080/WSTiempoAire/paqTiempoAire/2/comprar',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPROVEEDORTELE(FIIDPROVEEDOR, FCNOMBRE, FCURLWSCOMPRAPAQ, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(3, 'AT&T', 'http://localhost:8080/WSTiempoAire/paqTiempoAire/3/comprar',1, NOW(), NOW(), 'USRBASE');

/* Registramos algunos paquetes de proveedores */
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(1, 20, 'PAQUETE DE $20',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(1, 30, 'PAQUETE DE $30',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(1, 50, 'PAQUETE DE $50',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(1, 100, 'PAQUETE DE $100',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(1, 200, 'PAQUETE DE $200',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(1, 500, 'PAQUETE DE $500',1, NOW(), NOW(), 'USRBASE');

INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(2, 10, 'PAQUETE DE $10',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(2, 20, 'PAQUETE DE $20',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(2, 50, 'PAQUETE DE $50',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(2, 100, 'PAQUETE DE $100',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(2, 200, 'PAQUETE DE $200',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(2, 300, 'PAQUETE DE $300',1, NOW(), NOW(), 'USRBASE');

INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(3, 20, 'PAQUETE DE $20',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(3, 50, 'PAQUETE DE $50',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(3, 100, 'PAQUETE DE $100',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(3, 150, 'PAQUETE DE $150',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(3, 200, 'PAQUETE DE $200',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(3, 300, 'PAQUETE DE $300',1, NOW(), NOW(), 'USRBASE');
INSERT INTO TCPAQUETES(FIIDPROVEEDOR, FIMONTO, FCDESCRIPCION, FIESTATUS, FDFECHAALTA, FDFECHAMODIFICACION, FCUSUARIO)
VALUES(3, 500, 'PAQUETE DE $500',1, NOW(), NOW(), 'USRBASE');

/* Fin de INSERTs*/